version: '2.1'

services:

  geth-rinkeby:
    image: ethereum/client-go:v1.10.8
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - ${PWD}/rinkeby:/.rinkeby
    command: "--rinkeby --rpc --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .rinkeby --verbosity 3"

  geth-mainnet:
    image: ethereum/client-go:v1.10.8
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - ${PWD}/mainnet:/.mainnet
    command: "--rpc  --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .mainnet --verbosity 3"
