version: '3'
services:
  pocket-service:
    image: poktnetwork/pocket-core:RC-0.6.2
    command: pocket start --mainnet --datadir=/home/app/.pocket
    ports:
      - "xxxx:8081"
      - "xxxx:26657"
      - "xxxx:26656"
    environment:
      POCKET_CORE_CHAINS: '[{"id": "xxxx", "url": "http://host:port"}]'
      POCKET_CORE_KEY: <private key>
      POCKET_CORE_PASSPHRASE: <passphrase>
    networks:
      - pocket
    volumes:
      - pocket:/path/to/datadir
volumes:
  pocket:
networks:
  pocket:
    driver: bridge